### ISSUE TITLE
Is it possible to use sdepy to fit OU? 

### ISSUE THREAD

**Issue by mghadam** [sdepy/sdepy#43]
I read [the docs](https://sdepy.readthedocs.io/en/v1.1.2/) and couldn't find any information regarding this, is it possible to use sdepy to fit an Ornstein-Uhlenbeck process (in a numpy array) and get the relavant parameters mu, sigma and theta?

**Comment by m-cip** [comment]
Sdepy is about simulation of SDEs, and does not include facilities for parameters fitting. Unfortunately, I am not aware of any ready-made fitting tool tailored to the Ornstein-Uhlenbeck process I can point you at - does not mean there might not be any around, of course...

The statistical prowess you may want to throw at the problem may vary depending on your context; however, once you have a statistical estimation procedure of your liking, you may use sdepy to validate how it performs on simulated data, e.g. to see if 95% confidence intervals of estimates do indeed hit the spot 95 times out of 100. This is particularly relevant if your problem is not exactly Ornstein-Uhlenbeck, and you want to test the robustness of your procedures under different scenarios (i.e., different simulated SDEs).

**Comment by mghadam** [comment]
Thank you for your thorough comment,[ it appears](https://www.statisticshowto.com/wp-content/uploads/2016/01/Calibrating-the-Ornstein.pdf) that there are two common methods for fitting an OU process, the least squares regression method and the maximum likelihood method. 
I found [ou_noise](https://github.com/jwergieluk/ou_noise) python package which uses the latter.
