### ISSUE TITLE
An incompatibility of sdepy with numpy?

### ISSUE THREAD

**Issue by mikewojnowicz** [sdepy/sdepy#44]
Hi,

I have attempted to follow the tutorial to construct a linear SDE with time-invariant parameters as follows.

```
import sdepy 
@sdepy.integrate
def my_process(t, x, A_bar=np.eye(2), L_bar=np.eye(2)):
    """
    The SDE is dX_t = A_bar X_t dt + L_bar dB_t
    In other words, the diffusion matrix is Q_bar := L_bar @ L_bar.T
    """
    return {'dt': np.dot(A_bar,x), 'dw': L_bar}

coarse_timeline = np.arange(1,8+1).tolist()
np.random.seed(1)  # make doctests predictable
x = my_process(x0=np.array([1,0]), paths=10, steps=100)(coarse_timeline)
```

But I have received an error message that suggests that this package is not compatible with numpy.  Is that true?  Any suggestions on how to proceed?

```
In [14]: coarse_timeline = np.arange(1,8+1).tolist()
    ...: np.random.seed(1)  
    ...: x = my_process(x0=np.array([1,0]), paths=10, steps=100)(coarse_timeline)
    ...: 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[14], line 3
      1 coarse_timeline = np.arange(1,8+1).tolist()
      2 np.random.seed(1)  # make doctests predictable
----> 3 x = my_process(x0=np.array([1,0]), paths=10, steps=100)(coarse_timeline)

File ~/Repos/cts_time_series/env/lib/python3.8/site-packages/sdepy/integration.py:1104, in SDE.__init__(self, paths, vshape, dtype, rng, steps, i0, info, getinfo, method, **args)
   1100 self.vshape = _shape_setup(vshape)
   1102 # get default args by inspection
   1103 # (stored as private attributes)
-> 1104 self._inspect_args_defaults()
   1106 # consolidate given args with defaults
   1107 self._args = self._consolidate_args(**args)

File ~/Repos/cts_time_series/env/lib/python3.8/site-packages/sdepy/integration.py:1018, in SDE._inspect_args_defaults(self, sde_nvars)
   1016     for k, z in D.items():
   1017         defaults[k].append(z)
-> 1018 repeated = {k for k in defaults
   1019             if len(set(defaults[k])) > 1}
   1020 if repeated:
   1021     raise TypeError(
   1022             'two or more incompatible defaults found '
   1023             'for SDE parameter(s) {}'
   1024             .format(repeated))

File ~/Repos/cts_time_series/env/lib/python3.8/site-packages/sdepy/integration.py:1019, in <setcomp>(.0)
   1016     for k, z in D.items():
   1017         defaults[k].append(z)
   1018 repeated = {k for k in defaults
-> 1019             if len(set(defaults[k])) > 1}
   1020 if repeated:
   1021     raise TypeError(
   1022             'two or more incompatible defaults found '
   1023             'for SDE parameter(s) {}'
   1024             .format(repeated))

TypeError: unhashable type: 'numpy.ndarray'

```

**Comment by m-cip** [comment]
Thanks for pointing this out, I'll look into it soon

**Comment by m-cip** [comment]
No incompatibility was triggered by recent numpy versions, fortunately. Below is an explanation of what happened, and some working code examples showing how your equation should be restated.

Due to an undocumented and unneeded restriction (i.e., a bug), default values of SDEs defined via `@sdepy.integrate` must be hashable. This is going to be fixed, but the workaround is easy: define the SDE using immutable values, and pass arrays later to the `my_process` instantiation call (mutable default values may silently produce unintended results though, if modified during execution in some unrelated piece of code).

This said, to get a working SDE object some more tweaks are needed in your case:
1. Since `X` is not a scalar, the intended shape of process values must be declared explicitly as `vshape=(2,)`
2. The equation is computed across paths, hence the  `x` served to `{'dt': np.dot(A_bar, x), 'dw': L_bar}` during integration has shape `vshape + (paths,)`, i.e. `(2, 10)` in your example, and doesn't go well with the `A_bar` dot operation. The initial condition `x0` given to `my_process` must broadcast to such shape as well (this allows for path-dependent initial conditions, which may come in handy on occasion).
3. The 'dw' value `L_bar` gets multiplied component-wise with brownian motion increments, and any differently intended tensor operation must be explicitly  coded (no implicit `@` product).

The code below fixes 1. and 2., and works as long as `L_bar` is a scalar (renamed `scalar_L_bar` below):

    import sdepy
    import numpy as np
    
    @sdepy.integrate(q=0, sources={'dt', 'dw'})
    def my_process(t, x, A_bar=1, scalar_L_bar=1):
        """
        The SDE is dX_t = A_bar X_t dt + L_bar dB_t
        In other words, the diffusion matrix is Q_bar := L_bar @ L_bar.T
        """
        # add trailing paths axis to A_bar and do matrix algebra
        return {'dt': np.einsum('ijp,jp->ip', A_bar[..., np.newaxis], x), 
                'dw': scalar_L_bar,
               } 
    
Fixing 3. is easy as well, but cannot be done with a one-liner, nor with the most self-evident code in the world (it gets the thing done, though): the most orderly approach is to build a stochasticity source that provides `L_bar @ dB_t`, and plug it into `my_process` above. It might look like this:

    class my_process_dw:
        def __init__(self, paths, vshape, L_bar, rng=None):
            # needed to comply with the source protocol
            self.paths = paths
            self.vshape = vshape
            # needed upon call
            self.L_bar = L_bar
            self.dw = sdepy.wiener_source(paths=paths, vshape=vshape, rng=rng)

        def __call__(self, t, dt):
            return np.einsum('ijp,jp->ip', self.L_bar[..., np.newaxis], self.dw(t, dt))

    rng = np.random.default_rng(1)
    coarse_timeline = np.arange(1, 8 + 1)   
    p = my_process(x0=np.array([1, 0]).reshape(-1, 1), 
                   A_bar=np.eye(2), scalar_L_bar=1,
                   dw=my_process_dw(paths=10, vshape=(2,), L_bar=np.eye(2), rng=rng),
                   paths=10, vshape=(2,), steps=100)
    x = p(coarse_timeline)

If you get further anomalous behavior let me know
